FROM rust:1.70-alpine3.17 as builder
WORKDIR /build
RUN apk add alpine-sdk
COPY . .
RUN cargo build --release

FROM alpine:3.17
WORKDIR /fn
COPY --from=builder  /build/target/release/{FUNCTION_NAME} .
CMD ["./{FUNCTION_NAME}"]
