FROM fnproject/rust:1.70-build as builder
WORKDIR /build

COPY . .
RUN cargo build --release

FROM fnproject/rust:1.10-rt

RUN \
   ln -sf /usr/share/zoneinfo/Europe/Brussels /etc/localtime

WORKDIR /fn
COPY --from=builder  /build/target/release/{FUNCTION_NAME} .

ENV RUST_LOG=info
ENV RUST_BACKTRACE=full

CMD ["./{FUNCTION_NAME}"]
